<?php
$block = $this;
$interest = $block->getInterest();
?>
<p>
    <?php echo $block->getMessageBefore() ?>
<form class="form" action="<?php echo $block->getFormUrl() ?>" method="get" id="mailchimp-groups">
    <fieldset class="fieldset">
        <?php foreach($interest as $i):
            $this->setCurrentInterest($i); ?>
            <div class="field">
                <label class="label" for="<?php echo $i['interest']['id'] ?>">
                    <span><?php echo $i['interest']['title'] ?></span>
                </label>
                <div class="control">
                    <div class="fields">
                        <?php $this->getChild($blockName = "mailchimp.checkout.success.".$i['interest']['type'])->setCurrentInterest($i);
                        echo $this->getChildHtml($blockName, false);?>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit"
                    class="action primary"
                    title="<?php echo $block->escapeHtml(__('Subscribe to more detailed newsletters')) ?>">
                <span><?php echo __('Subscribe to more detailed newsletters') ?></span>
            </button>
        </div>
    </div>
</form>
<?php echo $block->getMessageAfter() ?>

</p>
