<?php
$block = $this;
$interest = $block->getInterest();
?>
<div class="fieldset">
    <?php foreach($interest as $i): ?>
        <ul class="form-list">
            <li class="field no-label">
            <label class="label" for="<?php echo $i['interest']['id'] ?>">
                <h4><?php echo $i['interest']['title'] ?></h4>
            </label>
            </li>
            <?php echo $this->getLayout()->createBlock('mailchimp/group_type', 'mailchimp.group.type', array('interests' => $i))->toHtml(); ?>
        </ul>
    <?php endforeach; ?>
</div>
