<?php
$block = $this;
$interest = $block->getInterest();
?>
<div class="fieldset">
    <?php foreach($interest as $i): ?>
        <ul class="form-list">
            <li>
            <label class="label" for="<?php echo $i['interest']['id'] ?>">
                <span><?php echo $i['interest']['title'] ?></span>
            </label>
            </li>
                    <?php switch($i['interest']['type']):
                        case 'checkboxes': ?>
                            <ul class="form-list" style="list-style: none">
                                <?php foreach($i['category'] as $c): ?>
                                    <li class="control">
                                        <input class="checkbox"
                                               name="group[<?php echo $i['interest']['id'] ?>][<?php echo $c['id']?>]"
                                               type="checkbox"
                                               value="<?php echo $c['id'] ?>"
                                               id="<?php echo 'mailchimp_group_'.$c['id'] ?>"
                                               title="<?php echo $c['name'] ?>"
                                            <?php if($c['checked']) { echo 'checked';} ?>
                                        />
                                        <label class=""><?php echo $c['name']?></label>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                            <?php       break;
                        case 'dropdown': ?>
                            <div class="field no-label">
                                <select class="dropdown"
                                        name="group[<?php echo $i['interest']['id'] ?>]"
                                        id="<?php echo 'mailchimp_group_'.$i['interest']['id'] ?>"
                                        title="<?php echo $i['interest']['title'] ?>">
                                    <option value=""></option>
                                    <?php foreach($i['category'] as $c): ?>
                                        <option value="<?php echo $c['id']?>" <?php if($c['checked']) { echo 'selected'; } ?>><?php echo $c['name'] ?></option>
                                    <?php endforeach; ?>
                                </select>

                            </div>
                            <?php       break;
                        case 'radio': ?>
                            <ul class="form-list">
                                <?php foreach($i['category'] as $c): ?>
                                    <li class="control" style="list-style: none">
                                        <input class="radio"
                                               name="group[<?php echo $i['interest']['id'] ?>]"
                                               type="radio"
                                               value="<?php echo $c['id'] ?>"
                                               id="<?php echo 'mailchimp_group_'.$c['id'] ?>"
                                               title="<?php echo $c['name'] ?>"
                                            <?php if($c['checked']) { echo 'checked';} ?>
                                        />
                                        <label class=""><?php echo $c['name']?></label>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                            <?php       break; ?>
                        <?php endswitch; ?>
                </div>
            </div>
        </ul>
    <?php endforeach; ?>
</li>
</div>
