<?php
$block = $this;
$i = $this->getCurrentInterest();
?>
<ul class="admin_field_field field" style="list-style: none">
<?php foreach ($i['category'] as $c): ?>
    <li class="control">
        <input class="checkbox"
               name="group[<?php
                    echo $this->escapeHtml($i['interest']['id'])
               ?>][<?php
                    echo $this->escapeHtml($c['id'])
               ?>]"
               type="checkbox"
               value="<?php echo $this->escapeHtml($c['id']) ?>"
               id="<?php echo $this->escapeHtml('mailchimp_group_'.$c['id']) ?>"
               title="<?php echo $this->escapeQuote($c['name']) ?>"
            <?php if ($c['checked']) {
                    echo $this->escapeHtml('checked');
            }
            ?>
        />
        <label for="<?php echo $this->escapeHtml('mailchimp_group_'.$c['id']) ?>" class="field label">
            <?php echo $this->escapeQuote($c['name'])?>
        </label>
    </li>
<?php endforeach; ?>
</ul>
