<?php
$block = $this;
$i = $this->getCurrentInterest();
?>
<div class="field no-label">
    <select class="field"
            name="group[<?php echo $this->escapeHtml($i['interest']['id']) ?>]"
            id="<?php echo $this->escapeHtml('mailchimp_group_'.$i['interest']['id']) ?>"
            title="<?php echo $this->escapeHtml($i['interest']['title']) ?>">
        <option value=""></option>
        <?php foreach ($i['category'] as $c): ?>
            <option value="<?php echo $this->escapeHtml($c['id']) ?>" <?php if ($c['checked']) {
                echo 'selected';
           }
        ?>><?php echo $this->escapeQuote($c['name']) ?></option>
        <?php endforeach; ?>
    </select>
</div>
