<?php
/**
 * @see Ebizmarts_MailChimp_Block_Adminhtml_System_Config_Form_Field_Mapfields
 */
?>

<?php
$htmlId = $this->getHtmlId() ? $this->getHtmlId() : '_' . uniqid();
$colspan = 2;
if (!$this->_addAfter) {
    $colspan--;
}

$colspan = $colspan > 1 ? 'colspan="' . $colspan . '"' : '';
?>

<div class="grid" id="grid<?php echo $this->escapeQuote($htmlId) ?>">
    <table cellpadding="0" cellspacing="0" class="border">
        <tbody>

        <tr class="headings" id="headings<?php echo $this->escapeQuote($htmlId) ?>">
            <?php foreach ($this->_columns as $columnName => $column): ?>
                <th><?php echo $this->escapeQuote($column['label']) ?></th>
            <?php endforeach; ?>
            <th <?php echo $this->escapeQuote($colspan) ?>></th>
        </tr>

        <tr id="addRow<?php echo $this->escapeQuote($htmlId) ?>">
            <td colspan="<?php echo $this->escapeQuote(count($this->_columns)) ?>">
                <button style=""
                        onclick=""
                        class="scalable add"
                        type="button"
                        id="addNewType<?php echo $this->escapeQuote($htmlId) ?>">
                    <span>
                        <span>
                            <span>
                                <?php echo $this->escapeQuote(
                                    Mage::helper('mailchimp')->__(
                                        'Add new custom data entry in the column of the right'
                                    )
                                ) ?>
                            </span>
                        </span>
                    </span>
                </button>
            </td>
            <td <?php echo $this->escapeQuote($colspan) ?>>
                <button style=""
                        onclick=""
                        class="scalable add"
                        type="button"
                        id="addToEndBtn<?php echo $this->escapeQuote($htmlId) ?>">
                    <span>
                        <span>
                            <span>
                                <?php echo $this->escapeQuote(Mage::helper('mailchimp')->__('Add new row')) ?>
                            </span>
                        </span>
                    </span>
                </button>
            </td>
        </tr>

        </tbody>
    </table>
    <input type="hidden" name="<?php echo $this->escapeQuote($this->getElement()->getName()) ?>[__empty]" value=""/>
</div>
<div id="empty<?php echo $this->escapeQuote($htmlId) ?>">
    <button style=""
            onclick=""
            class="scalable add"
            type="button"
            id="emptyAddBtn<?php echo $this->escapeQuote($htmlId) ?>">
        <span>
            <span>
                <span>
                    <?php echo $this->escapeQuote($this->_addButtonLabel) ?>
                </span>
            </span>
        </span>
    </button>
</div>

<script type="text/javascript">
    // create row creator
    var arrayRow<?php echo $this->escapeQuote($htmlId) ?> = {
        // define row prototypeJS template
        template: new Template(
            '<tr id="#{_id}">'
            <?php foreach ($this->_columns as $columnName => $column):?>
            + '<td>'
            + '<?php echo $this->jsQuoteEscape($this->_renderCellTemplate($columnName)) ?>'
            + '<\/td>'
            <?php endforeach;?>
            <?php if ($this->_addAfter):?>
            + '<td><button onclick="" class="scalable add" type="button" id="addAfterBtn#{_id}"><span><span><span>'
            +<?php
            echo $this->jsQuoteEscape(Mage::helper('adminhtml')->__('Add after'))?>
            +'<\/span><\/span><\/span><\/button><\/td>'
            <?php endif;?>
            + '<td><button onclick="arrayRow<?php echo $this->escapeQuote($htmlId) ?>.del(\'#{_id}\')" '
            + 'class="scalable delete" type="button"><span><span><span>'
            + '<?php echo $this->jsQuoteEscape(Mage::helper('adminhtml')->__('Delete')) ?>'
            + '<\/span><\/span><\/span><\/button><\/td>'
            + '<\/tr>'
        ),
        rowsCount: 0,
        add: function (templateData, insertAfterId) {
            if (this.rowsCount >= 30) {
                alert("Max. merge fields reached. \nOnly up to 30 merge fields are allowed.");
            } else {
                // generate default template data
                if ('' == templateData) {
                    var d = new Date();
                    templateData = {
                        <?php foreach ($this->_columns as $columnName => $column):?>
                        <?php echo $this->escapeQuote($columnName) ?>: '',
                        <?php endforeach;?>
                        _id: '_' + d.getTime() + '_' + d.getMilliseconds()
                    };
                }
                // insert before last row
                if ('' == insertAfterId) {
                    Element.insert(
                        $('addRow<?php echo $this->escapeQuote($htmlId) ?>'),
                        {before: this.template.evaluate(templateData)});
                }
                // insert after specified row
                else {
                    Element.insert($(insertAfterId), {after: this.template.evaluate(templateData)});
                }
                // set the selected drop-down list item
                <?php foreach ($this->_columns as $columnName => $column):?>
                <?php if($columnName == 'magento'):?>
                $$('select[name*=' + templateData._id + ']').each(function (row) {
                    var oldText = 'value="' + templateData.<?php echo $this->escapeQuote($columnName) ?>+ '"';
                    var newText = 'selected="selected" value="'
                        + templateData.<?php echo $this->escapeQuote($columnName) ?>
                        + '"';
                    row.innerHTML = row.innerHTML.replace(oldText, newText);
                });
                <?php endif; ?>
                <?php endforeach;?>
                <?php if ($this->_addAfter):?>
                Event.observe('addAfterBtn' + templateData._id, 'click', this.add.bind(this, '', templateData._id));
                <?php endif;?>
                this.rowsCount += 1;
            }
        },
        open: function () {
            var url = '<?php echo $this->escapeUrl($this->getUrl("adminhtml/mergevars/addmergevar/")) ?>?';
            var dialogWindow = Dialog.info(null, {
                draggable: true,
                resizable: false,
                closable: true,
                className: "magento",
                windowClassName: "popup-window",
                title: 'Add new Merge Var to send to Mailchimp',
                top: 50,
                width: 1000,
                height: 300,
                zIndex: 1000,
                recenterAuto: false,
                hideEffect: Element.hide,
                showEffect: Element.show,
                id: "browser_window",
                url: url,
                onClose: function (param, el) {
                    location.reload();
                }
            });
        },
        del: function (rowId) {
            $(rowId).remove();
            this.rowsCount -= 1;
            if (0 == this.rowsCount) {
                this.showButtonOnly();
            }
        },
        showButtonOnly: function () {
            $('grid<?php echo $this->escapeQuote($htmlId) ?>').hide();
            $('empty<?php echo $this->escapeQuote($htmlId) ?>').show();
        }
    };
    // bind add action to "Add" button in last row
    Event.observe(
        'addToEndBtn<?php echo $this->escapeQuote($htmlId) ?>',
        'click',
        arrayRow<?php echo $this->escapeQuote($htmlId) ?>.add.bind(
            arrayRow<?php echo $this->escapeQuote($htmlId) ?>,
            '',
            ''
        )
    );
    Event.observe(
        'addNewType<?php echo $this->escapeQuote($htmlId) ?>',
        'click',
        arrayRow<?php echo $this->escapeQuote($htmlId) ?>.open.bind(this)
    );
    // add existing rows
    <?php
    $addAfterId = "headings{$htmlId}";
    foreach ($this->getArrayRows() as $rowId => $row) {
        echo $this->escapeQuote("arrayRow{$htmlId}.add(")
            . $this->jsQuoteEscape($row->toJson())
            . $this->jsQuoteEscape(", {$addAfterId});\n");
        $addAfterId = $rowId;
    }
    ?>
    // initialize standalone button
    $('empty<?php echo $this->escapeQuote($htmlId) ?>').hide();
    Event.observe('emptyAddBtn<?php echo $this->escapeQuote($htmlId) ?>', 'click', function () {
        $('grid<?php echo $this->escapeQuote($htmlId) ?>').show();
        $('empty<?php echo $this->escapeQuote($htmlId) ?>').hide();
        arrayRow<?php echo $this->escapeQuote($htmlId) ?>.add('', '');
    });
    // if no rows, hide grid and show button only
    <?php if (!$this->getArrayRows()):?>
    arrayRow<?php echo $this->escapeQuote($htmlId) ?>.showButtonOnly();
    <?php endif;?>
    // toggle the grid, if element is disabled (depending on scope)
    <?php if ($this->getElement()->getDisabled()):?>
    toggleValueElements({checked: true}, $('grid<?php echo $this->escapeQuote($htmlId) ?>').parentNode);
    <?php endif;?>
</script>
