<?php
/**
 * @see Ebizmarts_MailChimp_Block_Adminhtml_System_Config_Fieldset_Hint
 */
?>
<div class="mailchimp-notice">
    <img width="250px" height="56.8px" src="<?php echo $this->getSkinUrl('images/ebizmarts/Logo_Ebizmarts.png'); ?>"/>
    <h4>
        <?php echo Mage::helper('mailchimp')->__('<strong style="color:#EA7601;">MailChimp For Magento v%s by</strong> <a target="_blank" href="http://ebizmarts.com"><strong>ebizmarts</strong></a>', $this->getMailChimpVersion()) ?>
        <br>
        <?php echo Mage::helper('mailchimp')->__('Need help? See our <a href="http://wiki.ebizmarts.com/installation" target="_blank">Wiki</a> or browse our <a href="http://ebizmarts.com/mailchimp-for-magento-support" target="_blank">support forums</a>') ?>
    </h4>
    <h3><a style="padding-top: 5px;padding-bottom:5px;padding-left: 30px;padding-right: 30px;background-color:#D75F07 ;color:white;font-weight: bold" href="http://www.mailchimp.com/signup?pid=ebizmarts&source=website" target="_blank">Subscribe for a free MailChimp Account!</a> </h3>
</div>