<?php
/**
 * @see Ebizmarts_MailChimp_Block_Adminhtml_System_Config_Fieldset_Hint
 */
?>
<div class="mandrill-notice">
    <img width="244px" height="60px" src="https://ebizmarts-website.s3.amazonaws.com/Logo_Ebizmarts.png"/>
    <h4>
        <strong style="color:#EA7601;">
        <?php echo $this->escapeHtml(
            Mage::helper('mailchimp')->__(
                'Mandrill For Magento v%s by',
                $this->getMandrillVersion()
            )
        ); ?>
        </strong>
        <a target="_blank" href="http://ebizmarts.com">
            <strong>ebizmarts</strong>
        </a>
        <br>
        <?php echo $this->escapeHtml(Mage::helper('mailchimp')->__('Need help? See our ')); ?>
        <a href="http://wiki.ebizmarts.com/installation" target="_blank">Wiki</a>
        <?php echo $this->escapeHtml(Mage::helper('mailchimp')->__('or browse our ')); ?>
        <a href="http://ebizmarts.com/mailchimp-for-magento-support" target="_blank">
            <?php echo $this->escapeHtml(Mage::helper('mailchimp')->__('support forums.')); ?>
        </a>
    </h4>
</div>
