<script type="text/javascript">
    function createMergeFields() {
        new Ajax.Request('<?php echo $this->escapeUrl($this->getAjaxCheckUrl()) ?>', {
            method: 'get',
            onSuccess: function (transport) {

                if (transport.responseText == 1) {
                    alert('The merge fields were successfully created.')
                }
                else if (transport.responseText == 2) {
                    alert("Max. merge fields reached. \nOnly up to 30 merge fields are allowed.");
                }
                else {
                    alert('<?php echo $this->escapeHtml($this->getMessageForMailchimpErrorLog()) ?>')
                }
            },
            onFailure: function () {
                alert('Something went wrong.')
            }
        });
    }
</script>


<?php echo $this->getButtonHtml(); ?>
