<script type="text/javascript">
    //<![CDATA[
    function createwebhook() {
        new Ajax.Request('<?php echo $this->getAjaxCheckUrl() ?>', {
            method: 'get',
            onSuccess: function (transport) {
                if (transport.responseText == true) {
                    alert('The webhook was created successfully')
                }
                else {
                    alert(transport.responseText)
                }
            },
            onFailure: function () {
                alert('Something went wrong.')
            }
        });
    }
    //]]>
</script>


<?php echo $this->getButtonHtml(); ?>
