<script type="text/javascript">
    //<![CDATA[
    function preshow() {
        <?php   $helper = Mage::helper('mailchimp');
            $scopeArray = $helper->getCurrentScope();
            $mailchimpStoreId = $helper->getMCStoreId($scopeArray['scope_id'], $scopeArray['scope']);
        ?>
        if($('mailchimp_general_list').value != '' && '<?php echo $mailchimpStoreId ?>' != 0) {
            $('mailchimp_general_list').setAttribute('disabled',true);
            $('changelist_button').setAttribute('style','display:yes');
        } else {
            $('changelist_button').setAttribute('style','display:none');
        }
    }
    function resetlist() {
        if(confirm('<?php echo $this->getPopupMessage(); ?>')) {
            $('mailchimp_general_list').removeAttribute('disabled');
            $('changelist_button').setAttribute('style','display:none');
            $('row_mailchimp_general_reset_list').down(9).setAttribute('style','display:none');
            //$('row_mailchimp_general_reset_list').childElements('value').childElements('p').setAttribute('style','display:none');
            Event.observe($('mailchimp_general_list'),'change',function() {
                $('row_mailchimp_general_reset_list').down(9).setAttribute('style','display:yes;color:red;padding:5px;font-weight:bold;');
                $('row_mailchimp_general_reset_list').down(9).update('<?php echo $this->getMessage() ?>');
                $('row_mailchimp_general_reset_list').down(8).className = '';
            });
        }
    }
    window.onload=preshow;
    //]]>

</script>


<?php echo $this->getButtonHtml(); ?>
